### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by erikmack** [CanonicalLtd/go-grpc-sql#5]
Is this public domain code?

**Comment by kitsuyui** [comment]
@erikmack 

Isn't this?
https://github.com/CanonicalLtd/go-grpc-sql/blob/master/COPYING

**Comment by freeekanayaka** [comment]
Note that this package is deprecated and not used anymore. We might eventually delete this repository as well, to avoid confusion.

**Comment by freeekanayaka** [comment]
And the license is what @kitsuyui pointed.

**Comment by erikmack** [comment]
Thank you.  I see Stephane eventually added the license, and since then the package is no longer an lxd dependency.  

As the lxd packager for a distribution, it was important at the time to account for the licenses of all the libs used.
